<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Crosio.Windows.Capture</RootNamespace>
    <AssemblyName>Crosio.Windows.Capture</AssemblyName>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
  </PropertyGroup>
</Project>
